[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements_production.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --settings=toyota_training.settings_production"
]

[start]
cmd = "gunicorn toyota_training.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 2 --timeout 30"

