[tool.ruff]
line-length = 100
select = [
  "E", "F", "I"
]

[tool.mypy]
python_version = 3.11
plugins = []
ignore_missing_imports = true
warn_unused_ignores = true
strict_optional = true

[tool.black]
line-length = 100
