# Generated by Django 4.2.25 on 2025-10-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name for the program (e.g., PA465, PA466)', max_length=100)),
                ('title', models.CharField(help_text='Full title of the training program (e.g., PA465 2026 bZ Virtual Training)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the training program')),
                ('main_image', models.ImageField(help_text='Main image for this training program', upload_to='training_programs/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this training program is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='title',
        ),
        migrations.AddField(
            model_name='trainingpage',
            name='current_program',
            field=models.ForeignKey(blank=True, help_text='The currently active training program for this region', null=True, on_delete=django.db.models.deletion.PROTECT, to='training_app.trainingprogram'),
        ),
    ]
