# Generated by Django 4.2.25 on 2025-10-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0002_trainingprogram_remove_trainingpage_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_regions',
            field=models.ManyToManyField(blank=True, help_text='Training pages this admin user can manage (only applies to admin users)', to='training_app.trainingpage'),
        ),
    ]
