# Generated by Django 4.2.25 on 2025-10-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0003_customuser_assigned_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='training_program',
            field=models.ForeignKey(blank=True, help_text='Which training program this session is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_app.trainingprogram'),
        ),
    ]
