# Generated by Django 4.2.25 on 2025-10-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0004_trainingsession_training_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='teams_link',
            field=models.URLField(blank=True, help_text='Microsoft Teams meeting link', max_length=500),
        ),
    ]
