# Generated by Django 4.2.25 on 2025-10-03 19:36

from django.db import migrations, models
import training_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0005_increase_teams_link_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpage',
            name='region',
            field=models.CharField(choices=[('quebec', 'Quebec'), ('central', 'Central'), ('pacific', 'Pacific'), ('prairie', 'Prairie'), ('atlantic', 'Atlantic')], help_text='The region this training page is for', max_length=20, unique=True, validators=[training_app.validators.validate_region]),
        ),
        migrations.AlterField(
            model_name='trainingpage',
            name='timezone',
            field=models.CharField(default='America/Toronto', help_text='Timezone for this region (EST/EDT)', max_length=50, validators=[training_app.validators.validate_timezone]),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='main_image',
            field=models.ImageField(help_text='Main image for this training program', upload_to='training_images/'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(help_text='Date of the training session', validators=[training_app.validators.validate_training_session_date]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='teams_link',
            field=models.URLField(blank=True, help_text='Microsoft Teams meeting link', max_length=500, validators=[training_app.validators.validate_teams_link]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='time_est',
            field=models.TimeField(help_text='Time of the training session (Eastern Time)', validators=[training_app.validators.validate_training_session_time]),
        ),
    ]
