# Generated by Django 4.2.25 on 2025-10-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0006_alter_trainingpage_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='main_image',
            field=models.ImageField(help_text='Main image for this training program', upload_to='training_programs/'),
        ),
    ]
