# Generated by Django 4.2.25 on 2025-10-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0007_alter_trainingprogram_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image for this training program', null=True, upload_to='training_programs/'),
        ),
    ]
