# Generated by Django 4.2.25 on 2025-10-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0008_alter_trainingprogram_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='title_fr',
            field=models.CharField(blank=True, help_text='French title (used for Quebec page if provided)', max_length=200),
        ),
    ]
